### ISSUE TITLE
CSV and other raw data files are missing from project.

### ISSUE THREAD

**Issue by jgimbel** [ntguardian/dataviscourse-pr-congressrelations#1]
SenateVote114.csv,  data is missing from this project. The files are used on Lines [20](https://github.com/ntguardian/dataviscourse-pr-congressrelations/blob/master/CS6630ReadData-12-2-15.R#L20), [59](https://github.com/ntguardian/dataviscourse-pr-congressrelations/blob/master/CS6630ReadData-12-2-15.R#L59), and[74](https://github.com/ntguardian/dataviscourse-pr-congressrelations/blob/master/CS6630ReadData-12-2-15.R#L74) of the Read Data file.
I would suggest making another directory to store data that needs to be pre-processed, and adding that to the gulp build.

**Comment by ntguardian** [comment]
Resolved: raw data has been added in the raw_data directory.
